apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: celine-mqtt-auth

build:
  artifacts:
    - image: ghcr.io/celine-eu/celine-policies
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useDockerCLI: true
  tagPolicy:
    sha256: {}
