version: "3"

tasks:
  setup:
    desc: Setup
    cmds:
      - uv sync

  run:
    desc: "Run development server"
    cmds:
      - .venv/bin/uvicorn celine.mqtt_auth.main:create_app --reload --host 0.0.0.0 --port 8009

  debug:
    desc: "Run development server with debugger"
    cmds:
      - DEBUG_ATTACH=nowait DEBUG_PORT=48009 .venv/bin/uvicorn celine.mqtt_auth.main:create_app --reload --host 0.0.0.0 --port 8009

  test:
    desc: "Run test"
    cmds:
      - uv run pytest

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags

  keycloak:bootstrap:
    cmds:
      - uv run celine-policies keycloak sync

  keycloak:sync:
    deps: [keycloak:bootstrap]
    cmds:
      - uv run celine-policies keycloak bootstrap --admin-user admin --admin-password admin

  keycloak:sync-users:
    deps: [keycloak:bootstrap]
    desc: "Sync Keycloak users from REC registry YAML"
    vars:
      REC_YAML: '{{.CLI_ARGS | default "../rec-registry/recs/rec-example.yaml"}}'
    cmds:
      - uv run celine-policies keycloak sync-users {{.REC_YAML}}

  keycloak:sync-orgs:
    deps: [keycloak:bootstrap]
    desc: "Sync Keycloak organizations from owners yaml"
    vars:
      REC_YAML: '{{.CLI_ARGS | default "../dataset-api/owners.yaml"}}'
    cmds:
      - uv run celine-policies keycloak sync-orgs {{.REC_YAML}}
