"""Pydantic models for Keycloak YAML configuration.

Example YAML structure:
    realm: celine

    scopes:
      - name: dataset.query
        description: Query datasets
      - name: dataset.admin
        description: Administer datasets

    clients:
      - client_id: svc-forecast
        name: Forecast Service
        description: Weather and energy forecasting
        secret: ${SVC_FORECAST_SECRET}  # optional, supports env vars
        scopes_prefix: forecast         # owns all forecast.* scopes
        default_scopes:
          - forecast.admin
          - dataset.query               # foreign scope → audience mapper added for svc-dataset-api
        optional_scopes:
          - digital-twin.values.read

      - client_id: celine-cli
        name: CELINE CLI / Services
        secret: ${CELINE_CLI_SECRET:-celine-cli}
        # No scopes_prefix — sudo client, exempt from auto audience mapper derivation.
        # extra_audiences explicitly lists each service this client calls so the
        # sync tool can still manage the aud-mapper-* protocol mappers for it.
        extra_audiences:
          - svc-dataset-api
          - svc-nudging
        default_scopes:
          - dataset.admin
          - nudging.admin

One realm may be declared by more than one file — see `merge_documents`. A second
file owns the clients it declares, and either file may add grants to a client the
other owns:

    # clients.yaml — this repository's own services
    requires: [ds]                    # refuse to sync without the 'ds' declaration
    clients:
      - client_id: svc-ds-onboarding  # grants only: ds owns this client
        default_scopes:
          - rec-registry.members.write

    # clients.ds.yaml — supplied with --overlay, generated by another repository
    overlay: ds
    clients:
      - client_id: svc-ds-onboarding
        name: DS Onboarding
        scopes_prefix: identity-registry
"""

from __future__ import annotations

import copy
import os
import re
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field, PrivateAttr, field_validator


# Pattern for ${VAR} and ${VAR:-default} interpolation
_ENV_PATTERN = re.compile("\\$\\{([A-Za-z_][A-Za-z0-9_]*)(:-([^}]*))?}")


def _resolve_env_str(s: str) -> str:
    """Resolve environment variable placeholders in a string."""

    def repl(m: re.Match[str]) -> str:
        var = m.group(1)
        default = m.group(3)
        val = os.getenv(var)
        if val is None or val == "":
            return default if default is not None else ""
        return val

    # Resolve repeatedly until stable (handles nested defaults)
    prev = None
    cur = s
    for _ in range(5):
        if cur == prev:
            break
        prev = cur
        cur = _ENV_PATTERN.sub(repl, cur)
    return cur


def _resolve_env(value: Any) -> Any:
    """Recursively resolve environment variables in a data structure."""
    if isinstance(value, str):
        return _resolve_env_str(value)
    if isinstance(value, list):
        return [_resolve_env(v) for v in value]
    if isinstance(value, dict):
        return {k: _resolve_env(v) for k, v in value.items()}
    return value


class ScopeConfig(BaseModel):
    """Configuration for a client scope."""

    name: str = Field(..., description="Scope name (e.g., 'dataset.query')")
    description: str = Field(default="", description="Human-readable description")
    protocol: str = Field(
        default="openid-connect", description="Protocol (usually openid-connect)"
    )

    # Additional attributes that can be set
    include_in_token_scope: bool = Field(
        default=True,
        description="Whether to include scope in access token",
    )


class ClientConfig(BaseModel):
    """Configuration for a Keycloak client."""

    client_id: str = Field(..., description="Client ID (unique identifier)")
    name: str = Field(default="", description="Display name")
    description: str = Field(default="", description="Description")

    # Secret management
    secret: str | None = Field(
        default=None,
        description="Client secret (if not provided, will be generated)",
    )

    # Scope ownership declaration.
    # Scopes starting with this prefix belong to this client.
    # Used to derive audience mappers: any other client referencing a foreign
    # scope prefix gets an audience mapper pointing to the owning client.
    # Clients without a scopes_prefix (e.g. celine-cli, mqtt-only clients)
    # are exempt from auto audience mapper derivation.
    scopes_prefix: str | None = Field(
        default=None,
        description=(
            "Scope prefix this client owns (e.g. 'dataset' owns all 'dataset.*' scopes). "
            "Drives automatic audience mapper generation for cross-service calls."
        ),
    )

    # Explicit audience mappers for clients without a scopes_prefix.
    # The sync tool will create one aud-mapper-* protocol mapper per entry,
    # regardless of scopes_prefix being set or not.
    # For clients WITH a scopes_prefix, foreign_scope_prefixes() covers this
    # automatically — extra_audiences is an escape hatch for anything that
    # cannot be derived from scope names alone.
    extra_audiences: list[str] = Field(
        default_factory=list,
        description=(
            "Explicit audience client_ids to add as protocol mappers. "
            "Used for sudo/CLI clients that have no scopes_prefix and cannot "
            "rely on automatic audience derivation from foreign scope prefixes."
        ),
    )

    # Scope assignments
    default_scopes: list[str] = Field(
        default_factory=list,
        description="Scopes always included in tokens",
    )
    optional_scopes: list[str] = Field(
        default_factory=list,
        description="Scopes included only when explicitly requested",
    )

    # Service account settings (always enabled for this CLI)
    service_account_enabled: bool = Field(
        default=True,
        description="Enable service account (client credentials flow)",
    )

    @field_validator("name", mode="before")
    @classmethod
    def default_name_from_client_id(cls, v: str, info) -> str:
        """Use client_id as default name if not provided."""
        if not v and info.data.get("client_id"):
            return info.data["client_id"]
        return v or ""

    def has_placeholder_secret(self) -> bool:
        """Whether this client's secret is a development placeholder.

        Two shapes, both produced by an unset environment variable:

        - ``secret == client_id`` — the ``${SVC_X_SECRET:-svc-x}`` fallback. Fine
          locally, but in a real realm it is a credential anyone can guess from
          the client list.
        - an empty secret — ``${SVC_X_SECRET}`` with nothing to resolve to. It is
          sent to Keycloak as no secret at all, so whatever was there before
          silently stays in force.

        ``None`` is not a placeholder: it means the YAML declares no secret and
        Keycloak generates a real one.
        """
        if self.secret is None:
            return False
        return not self.secret.strip() or self.secret == self.client_id

    def scope_prefix_of(self, scope_name: str) -> str:
        """Extract the service prefix from a scope name (part before first '.')."""
        return scope_name.split(".")[0]

    def foreign_scope_prefixes(self) -> set[str]:
        """Return scope prefixes referenced by this client that are not its own.

        These are the services this client needs to call, and therefore the
        audience mappers that need to be added to its tokens.

        Returns empty set for clients without a scopes_prefix (they are exempt
        from auto-derivation; use extra_audiences instead).
        """
        if self.scopes_prefix is None:
            return set()

        all_scopes = list(self.default_scopes) + list(self.optional_scopes)
        prefixes: set[str] = set()
        for scope in all_scopes:
            prefix = self.scope_prefix_of(scope)
            if prefix != self.scopes_prefix:
                prefixes.add(prefix)
        return prefixes

    def desired_audiences(self, prefix_to_client: dict[str, str]) -> set[str]:
        """Return the complete set of audience client_ids this client needs.

        Combines:
          - Audiences derived from foreign scope prefixes (for clients with scopes_prefix)
          - Explicitly declared extra_audiences (for all clients, especially sudo clients)
        """
        audiences: set[str] = set(self.extra_audiences)

        for prefix in self.foreign_scope_prefixes():
            owning_client = prefix_to_client.get(prefix)
            if owning_client:
                audiences.add(owning_client)

        return audiences


# ---------------------------------------------------------------------------
# Merging: one realm, more than one file that declares it
# ---------------------------------------------------------------------------
#
# `sync` recomputes the grants of every client *present* in the file it is
# given, so a file that describes only part of a realm does not leave the rest
# alone — it silently narrows the clients it does mention. The celine realm
# carries celine's own services **and** the dataspace services that `ds` owns,
# and neither repository can write the other's half. So the sync takes more
# than one file and merges them before anything else happens.
#
# The rule is **ownership, not precedence**. No file is subordinate to another
# and there is no last-wins:
#
#   * a client's identity is declared by exactly one file;
#   * any file may add grants to a client another file declares;
#   * a scope is declared once, or identically more than once;
#   * a realm-level key may be stated by any file, and two may not disagree.
#
# Merging happens over the **raw** documents, before interpolation, so that
# `_resolve_env` runs once over the result and `_raw_secrets` is captured from
# the merged text. See `KeycloakConfig._from_raw`.


class MergeError(ValueError):
    """Two files disagree about something exactly one of them may declare.

    Every message names both files and the key. The operator's next question is
    always which file to edit, and a merge error that does not answer it makes
    them go and diff two YAML documents by hand.

    A `ValueError` because that is what `from_yaml` already raises for a
    malformed document, and callers that catch one should catch the other.
    """


#: The only keys a file may carry on a client another file declares. An entry
#: holding `client_id` plus nothing but these is a *grant*: it widens a client
#: without claiming to own it. Anything else — `name`, `secret`, `scopes_prefix`,
#: `service_account_enabled`, or a key this model does not recognise — is a
#: statement about the client's identity, and identity has exactly one owner.
GRANT_KEYS = ("default_scopes", "optional_scopes", "extra_audiences")

#: `overlay: ds` names what a file supplies; `requires: [ds]` names what a sync
#: of this file cannot be correct without. Both are statements about the split
#: rather than about the realm, so `overlay` is dropped from the merged document
#: and `requires` survives as the union — see `_check_declared_overlays`.
OVERLAY_KEY = "overlay"
REQUIRES_KEY = "requires"


def load_raw_document(path: str | Path) -> dict[str, Any]:
    """Read one YAML file as it is written, without interpolating anything.

    Interpolation is deliberately not done here: it happens once, over the
    merged document, so that a value substituted into one file cannot change
    how another file merges into it.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    raw = yaml.safe_load(p.read_text())
    if not isinstance(raw, dict):
        raise ValueError(f"Config file must be a YAML mapping: {path}")
    return raw


def _merge_scope(
    merged: dict[str, Any],
    entries: dict[str, dict[str, Any]],
    sources: dict[str, str],
    source: str,
    entry: Any,
) -> None:
    """Add one scope, accepting an identical redeclaration and refusing a conflict.

    ds's merge refuses *any* redeclaration. This one accepts a repeat that says
    the same thing, and the deviation is deliberate: the two files that will be
    merged in practice declare a large number of the same scopes today, and
    refusing outright would make the split a single flag-day cut. An identical
    definition is unambiguous, so allowing it lets a file shed its copies one
    release at a time. A *differing* definition is exactly the ambiguity worth
    failing on.
    """
    if not isinstance(entry, dict) or not isinstance(entry.get("name"), str):
        raise MergeError(f"{source}: a scope entry has no name")

    name = entry["name"]
    previous = entries.get(name)
    if previous is None:
        copied = copy.deepcopy(entry)
        entries[name] = copied
        sources[name] = source
        merged.setdefault("scopes", []).append(copied)
        return

    if previous != entry:
        raise MergeError(
            f"scope {name!r} is declared differently by {sources[name]} and {source} — "
            "a scope has one definition; an identical repeat is allowed, a conflicting "
            "one is not"
        )


def _merge_client(
    merged: dict[str, Any],
    targets: dict[str, dict[str, Any]],
    identity_sources: dict[str, str],
    source: str,
    entry: Any,
) -> None:
    """Fold one client entry into the merged document.

    An entry carrying anything beyond `client_id` and the grant keys declares
    the client, and a second file declaring it is an error naming both. An entry
    carrying only grants widens whatever another file declares — which is how a
    host keeps its own grant on a guest's client without claiming to own it.
    """
    if not isinstance(entry, dict) or not isinstance(entry.get("client_id"), str):
        raise MergeError(f"{source}: a client entry has no client_id")

    client_id = entry["client_id"]
    identity = sorted(set(entry) - {"client_id"} - set(GRANT_KEYS))

    if identity:
        owner = identity_sources.get(client_id)
        if owner == source:
            raise MergeError(
                f"{source} declares client {client_id!r} twice — "
                f"the second entry sets {identity}"
            )
        if owner is not None:
            raise MergeError(
                f"client {client_id!r} is declared by both {owner} and {source} "
                f"(which sets {identity}) — a client's identity is declared by exactly "
                "one file. A second file may add "
                f"{', '.join(GRANT_KEYS)} to it and nothing else"
            )
        identity_sources[client_id] = source

    target = targets.get(client_id)
    if target is None:
        target = {"client_id": client_id}
        targets[client_id] = target
        merged.setdefault("clients", []).append(target)

    for key, value in entry.items():
        if key == "client_id" or key in GRANT_KEYS:
            continue
        target[key] = copy.deepcopy(value)

    for key in GRANT_KEYS:
        additions = entry.get(key) or []
        if not additions:
            continue
        existing = target.setdefault(key, [])
        for value in additions:
            if value not in existing:
                existing.append(value)


def _merge_realm_key(
    merged: dict[str, Any],
    sources: dict[str, str],
    source: str,
    key: str,
    value: Any,
) -> None:
    """A key any file may state, and no two files may disagree about.

    `realm` and `oauth2_proxy_client` are the ones that exist; an unrecognised
    top-level key is held to the same rule rather than being dropped, because a
    file quietly losing a key it set is the failure this whole mechanism exists
    to avoid.
    """
    previous = sources.get(key)
    if previous is not None and merged.get(key) != value:
        raise MergeError(
            f"{previous} and {source} disagree about {key!r}: "
            f"{merged.get(key)!r} and {value!r}"
        )
    merged[key] = copy.deepcopy(value)
    sources[key] = source


def merge_documents(documents: Sequence[tuple[str, dict[str, Any]]]) -> dict[str, Any]:
    """Merge raw documents into the one document that describes the whole realm.

    `documents` is `(source, raw)` pairs; the source is whatever names the file
    to an operator — a path — and appears in every error message.

    **The merge of a single document is that document.** Every rule here can
    only fire on two entries that contradict each other, so a lone file passes
    through unchanged — with one exception, and it was always broken: a file
    declaring the same client twice.

    Whether the *set* of documents adds up to a whole realm is a different
    question, and not one the merge can answer: see `_check_completeness`.
    """
    merged: dict[str, Any] = {}
    scope_entries: dict[str, dict[str, Any]] = {}
    scope_sources: dict[str, str] = {}
    client_targets: dict[str, dict[str, Any]] = {}
    identity_sources: dict[str, str] = {}
    realm_key_sources: dict[str, str] = {}
    requires: list[str] = []

    for source, document in documents:
        if not isinstance(document, dict):
            raise ValueError(f"Config file must be a YAML mapping: {source}")

        for key, value in document.items():
            if key == "scopes":
                for entry in value or []:
                    _merge_scope(merged, scope_entries, scope_sources, source, entry)
            elif key == "clients":
                for entry in value or []:
                    _merge_client(
                        merged, client_targets, identity_sources, source, entry
                    )
            elif key == OVERLAY_KEY:
                # What the file supplies. A per-file statement: it does not
                # describe the realm, so it does not survive into the merge.
                continue
            elif key == REQUIRES_KEY:
                for name in value or []:
                    if name not in requires:
                        requires.append(name)
            else:
                _merge_realm_key(merged, realm_key_sources, source, key, value)

    if requires:
        merged[REQUIRES_KEY] = requires

    return merged


def _grants_without_an_owner(
    documents: Sequence[tuple[str, dict[str, Any]]],
) -> dict[str, list[str]]:
    """Clients that are granted something and declared by nobody.

    A grants-only entry says *another file owns this client*. When no supplied
    file does, either one is missing or the entry is a typo — and neither is
    visible downstream: the sync would create a client with an empty name and a
    generated secret, and report it as a creation like any other.
    """
    owned: set[str] = set()
    granted: dict[str, list[str]] = {}

    for source, document in documents:
        for entry in document.get("clients") or []:
            if not isinstance(entry, dict):
                continue
            client_id = entry.get("client_id")
            if not isinstance(client_id, str):
                continue
            if sorted(set(entry) - {"client_id"} - set(GRANT_KEYS)):
                owned.add(client_id)
            elif source not in granted.setdefault(client_id, []):
                granted[client_id].append(source)

    return {
        client_id: sources
        for client_id, sources in granted.items()
        if client_id not in owned
    }


def _check_completeness(
    documents: Sequence[tuple[str, dict[str, Any]]],
) -> None:
    """Refuse a sync whose files do not add up to a whole realm.

    Two ways they can fail to, both of them a file that was not supplied.

    Once a base file has shed the clients another file declares, syncing it
    alone no longer deletes those clients — orphans need `--prune` — it strips
    them back to whatever grants the base still carries, silently, with no flag
    involved. That is the failure this whole mechanism exists to prevent, and
    after the split it is one forgotten argument away.

    So a file states what it cannot be synced without (`requires: [ds]`), the
    file that answers it says so (`overlay: ds`), and a sync missing one fails
    before anything is authenticated. Matching is by name rather than by path
    because a deployment mounts a file wherever it likes.

    Only a caller that is about to *write* a realm asks for this. Reading one
    file of a split declaration to look a client id up is a legitimate thing to
    do, and `from_yaml` keeps doing it.
    """
    supplied: dict[str, str] = {}
    for source, document in documents:
        name = document.get(OVERLAY_KEY)
        if isinstance(name, str) and name:
            supplied[name] = source

    for source, document in documents:
        for name in document.get(REQUIRES_KEY) or []:
            if name in supplied:
                continue
            available = ", ".join(sorted(supplied)) or "none"
            raise MergeError(
                f"{source} requires the {name!r} declaration, which was not supplied "
                f"(supplied: {available}). Pass the file that declares "
                f"`{OVERLAY_KEY}: {name}` with --overlay. Syncing without it would "
                "strip every grant that file carries off the clients that stay, "
                "without deleting anything and without a flag"
            )

    orphans = _grants_without_an_owner(documents)
    if orphans:
        detail = "; ".join(
            f"{client_id} (granted by {', '.join(sources)})"
            for client_id, sources in sorted(orphans.items())
        )
        raise MergeError(
            f"no supplied file declares {detail}. An entry carrying only "
            f"{', '.join(GRANT_KEYS)} widens a client another file owns; nothing "
            "supplied owns it, so the sync would create a client with no name and a "
            "generated secret. Declare it, or supply the file that does"
        )


class KeycloakConfig(BaseModel):
    """Top-level configuration for Keycloak sync."""

    realm: str = Field(default="celine", description="Target realm")

    scopes: list[ScopeConfig] = Field(
        default_factory=list,
        description="Client scopes to create/sync",
    )

    clients: list[ClientConfig] = Field(
        default_factory=list,
        description="Clients to create/sync",
    )

    # If set, the sync tool will ensure this client (typically oauth2-proxy) has
    # hardcoded audience mappers for every service client (those with scopes_prefix),
    # so user JWTs pass audience validation on all services.
    oauth2_proxy_client: str | None = Field(
        default=None,
        description=(
            "Client ID of the oauth2-proxy Keycloak client. "
            "Audience mappers for all service clients are synced onto it."
        ),
    )

    # Declarations a sync of this file cannot be correct without, by the name
    # each of them gives itself in its own `overlay:` key. Enforced by
    # `from_yaml_files`, not by `from_yaml` — see `_check_completeness`.
    requires: list[str] = Field(
        default_factory=list,
        description=(
            "Names of further declarations this file must be synced together with. "
            "Each is supplied with --overlay and identifies itself with `overlay: <name>`."
        ),
    )

    # client_id -> the secret exactly as written in the YAML, before
    # interpolation. Kept so that a placeholder that resolved to nothing can be
    # reported as the variable an operator has to set, rather than as a value
    # they would have to go and look up.
    _raw_secrets: dict[str, str] = PrivateAttr(default_factory=dict)

    @classmethod
    def from_yaml(cls, path: str | Path) -> "KeycloakConfig":
        """Load configuration from a single YAML file with env var interpolation.

        Kept as it was, and still the right entry point for a caller that reads
        one file to look something up — `sync-orgs` and `sync-users` read client
        ids and scopes out of it rather than writing a realm from it, so a
        declaration this file says it needs is none of their business.

        `keycloak sync` uses `from_yaml_files` instead: it is the one that
        writes, so it is the one that has to refuse an incomplete picture. That
        is what `complete=False` means here — parse and merge, but do not ask
        whether these files add up to a realm.
        """
        return cls.from_yaml_files([path], complete=False)

    @classmethod
    def from_yaml_files(
        cls,
        paths: Sequence[str | Path],
        *,
        complete: bool = True,
    ) -> "KeycloakConfig":
        """Load one or more YAML files as a single realm declaration.

        The files are merged as raw documents — see `merge_documents` — and only
        then interpolated and validated, so every guard downstream (the
        placeholder-secret check, `validate_scope_references`) sees the whole
        realm rather than one file's view of it.

        With a single path and `complete=False` this is `from_yaml`, which is the
        compatibility requirement: the plan a one-file sync produces must not
        move.

        `complete` is what separates writing from reading. It asserts that these
        files are the *whole* realm — every declaration a supplied file says it
        needs is here, and no grant names a client nobody owns — and only a
        caller about to rewrite a realm can claim that.
        """
        if not paths:
            raise ValueError("At least one configuration file is required")

        documents = [(str(Path(path)), load_raw_document(path)) for path in paths]
        if complete:
            _check_completeness(documents)

        return cls._from_raw(merge_documents(documents))

    @classmethod
    def _from_raw(cls, raw: dict[str, Any]) -> "KeycloakConfig":
        """Interpolate, validate and check a merged (or single) raw document.

        Interpolation happens **here and once**, over the merged document, and
        `_raw_secrets` is captured from the same text — which is what makes a
        client declared in a second file report the variable an operator has to
        export, with no special case for where it came from.
        """
        raw_secrets = {
            entry["client_id"]: entry["secret"]
            for entry in raw.get("clients") or []
            if isinstance(entry, dict)
            and isinstance(entry.get("client_id"), str)
            and isinstance(entry.get("secret"), str)
        }

        # Resolve environment variables
        resolved = _resolve_env(raw)

        config = cls.model_validate(resolved)
        config._raw_secrets = raw_secrets

        contested = config.contested_scope_prefixes()
        if contested:
            detail = "; ".join(
                f"{prefix!r} claimed by {', '.join(client_ids)}"
                for prefix, client_ids in sorted(contested.items())
            )
            raise MergeError(
                f"two clients claim one scopes_prefix: {detail}. The prefix decides "
                "which client every audience mapper for those scopes points at, so a "
                "second claimant does not fail — it sends tokens to the wrong service"
            )

        return config

    def secret_source(self, client_id: str) -> str | None:
        """The environment variable a client's secret comes from, if any.

        ``${SVC_X_SECRET:-svc-x}`` → ``SVC_X_SECRET``. None when the secret is
        hardcoded, absent, or the config was not loaded from a file.
        """
        raw = self._raw_secrets.get(client_id)
        if not raw:
            return None
        match = _ENV_PATTERN.search(raw)
        return match.group(1) if match else None

    def clients_with_placeholder_secrets(self) -> list[str]:
        """Client IDs whose secret is a dev placeholder — see `has_placeholder_secret`.

        Checked before syncing a production realm: every entry here is a client
        whose credential is either guessable from its own name or missing.
        """
        return sorted(c.client_id for c in self.clients if c.has_placeholder_secret())

    def get_scope_names(self) -> set[str]:
        """Get all scope names defined in config."""
        return {s.name for s in self.scopes}

    def get_client_ids(self) -> set[str]:
        """Get all client IDs defined in config."""
        return {c.client_id for c in self.clients}

    def get_all_referenced_scopes(self) -> set[str]:
        """Get all scope names referenced by clients."""
        scopes: set[str] = set()
        for client in self.clients:
            scopes.update(client.default_scopes)
            scopes.update(client.optional_scopes)
        return scopes

    def get_service_client_ids(self) -> set[str]:
        """Return client_ids of all service clients (those with a scopes_prefix).

        These are the clients that validate the 'aud' claim in incoming JWTs,
        so oauth2_proxy needs a mapper for each of them.
        """
        return {c.client_id for c in self.clients if c.scopes_prefix is not None}

    def build_prefix_to_client_map(self) -> dict[str, str]:
        """Build a mapping from scope prefix to owning client_id.

        Only clients with a scopes_prefix declared are included.

        Example:
            {"dataset": "svc-dataset-api", "digital-twin": "svc-digital-twin", ...}
        """
        return {
            c.scopes_prefix: c.client_id
            for c in self.clients
            if c.scopes_prefix is not None
        }

    def contested_scope_prefixes(self) -> dict[str, list[str]]:
        """Prefixes claimed by more than one client, which must be none.

        `build_prefix_to_client_map` is a dict comprehension, so a second
        claimant silently wins and every audience mapper derived from that
        prefix points at the wrong client — a token whose `aud` names a service
        that was never meant to receive it. Nothing checked this while one file
        described the whole realm and no single file exhibited it; merging two
        files makes it reachable, so `_from_raw` turns it into an error.
        """
        owners: dict[str, list[str]] = {}
        for client in self.clients:
            if client.scopes_prefix is not None:
                owners.setdefault(client.scopes_prefix, []).append(client.client_id)
        return {
            prefix: sorted(client_ids)
            for prefix, client_ids in owners.items()
            if len(client_ids) > 1
        }

    def validate_scope_references(self) -> list[str]:
        """Check that all scopes referenced by clients are defined.

        Returns list of undefined scope names.
        """
        defined = self.get_scope_names()
        referenced = self.get_all_referenced_scopes()

        # Standard Keycloak scopes that don't need to be defined
        builtin_scopes = {
            "openid",
            "profile",
            "email",
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt",
            "acr",
            "roles",
            "web-origins",
        }

        undefined = referenced - defined - builtin_scopes
        return sorted(undefined)
